version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    networks:
      - frontend
      - backend
    restart: always
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
